version: '3'

services:
  gallery:
    build: .
    depends_on:
      - 'database'
    ports:
      - '3001:3001'
    environment:
      restart: always

  database:
    build: database/
    environment:
      restart: always